title: Domspatzen Kurs Algorithmik
description: > # this means to ignore newlines until "baseurl:"
  Die Seite für die Kursmaterialien
permalink: ':title/'
baseurl: "/Algorithmik-Blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Rene Grünbauer# add your name

# Disqus
#discus-identifier: # add your discus identifier

# Tracker
#analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
